### ISSUE TITLE
Is this productions ready?

### ISSUE THREAD

**Issue by karneaud** [udamir/magx#3]
Hi,

I was looking for a simpler alternative to Colyseus and came across your package which seems to have what I am looking for...Is it production ready?

**Comment by udamir** [comment]
Hi, I am using this library in several projects that are now in production, but it still can have some bugs as it's not covered with tests. Also I don't have the documentation yet, but the code is full of comments. I had to develop magx as a transport for clinet-server state management sync - mosx, as integrating it into the colyseus was too complex task due to different approaches.

If you are going to use magx in you project be sure that I'm still support it. If you have any suggestions on how to improve it - please share, it will give me motivation to continue developing it.

**Comment by karneaud** [comment]
@udamir thanks for the feedback. But I just realised that it is written in Typescript. Can I still use it in pure JS projects?

**Comment by udamir** [comment]
yes, as any other packages in typescript)

**Comment by karneaud** [comment]
Thanks. I'll try it out.
